// Generated by info.scce.cinco.product.userdocumentation.codegen.MainGenerator
package info.scce.cinco.product.userdocgenerator.app
import java.io.File;
import java.io.IOException;
import java.io.IOException;
import java.util.Properties;
import org.openqa.selenium.By;
import java.io.FileInputStream;
import org.openqa.selenium.Keys;
import java.io.FileNotFoundException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.OutputType;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * 
 * 
 */
class Main {
	
	def static void main(String[] args) {
		
		}
	
	}
	
	/*================== Selenium Methods ==================*/

	public Boolean openBrowser(String sBrowserType)
	{
		this.driver.manage().window().maximize();
		return true;
	}
	public Boolean goToPage(String sSiteURL)
	{
		this.driver.get(sSiteURL);
		return true;
	}
	public Boolean takePageScreenshot(String folderName, String pictureName) throws IOException
	{
		//Use TakesScreenshot method to capture screenshot
		TakesScreenshot screenshot = (TakesScreenshot)this.driver;
		File source = screenshot.getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(source, new File("./"+folderName+"/" + pictureName + ".png"));
		return true;
	}
	public Boolean takeElementScreenshot(WebElement pElement, String folderName, String pictureName) throws IOException
	{
		//Capture single element screenshot
		File source = pElement.getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(source, new File("./"+folderName+"/" + pictureName + ".png"));
		return true;
	}
	public void highlightElement()
	{
		JavascriptExecutor jsExec = (JavascriptExecutor)this.driver;
		jsExec.executeScript("arguments[0].setAttribute('style','border: 2px solid red;');", this.element);
	}
	public Boolean typeIn(String elementID, String contentText)
	{
		WebElement inputField = this.driver.findElement(By.id(elementID));
		highlightElement(inputField);
		inputField.sendKeys(contentText + Keys.TAB);
		return true;
	}
	public Boolean pressEnter()
	{
		WebElement enterBtn = this.driver.findElement(By.xpath("//button[@type='submit']"));
		highlightElement(enterBtn);
		enterBtn.click();;
		return true;
	}
	public void closeBrowser()
	{
		this.driver.quit();
	}
}
